# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_recordvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordvideo',
            name='recorded_file',
            field=models.FileField(upload_to='recorded_video/webm/'),
        ),
    ]
